### DISCUSSION TITLE
I can't see developer settings in my dashboard

### DISCUSSION THREAD

**Discussion by edleeman17** [chartbrew/chartbrew#115] [Q&A] [answered]
Hi,

Sorry if this is a stupid question. I'm trying to install chartbrew into Strapi CMS. It's asking me for an API key. I've followed the tutorial on generating the API key, but I don't seem to have any developer settings on my self-hosted install. Is there an env variable I need to set to enable this?

![image](https://user-images.githubusercontent.com/61695425/174034042-bbf0bf05-6591-4944-9653-46336ca48353.png)

Many thanks,
Ed

**Comment by razvanilin** [comment, marked as answer]
Hey @edleeman17, do you have the latest version of Chartbrew up and running? The API Keys functionality was added in the v1.22.0

**Reply by edleeman17** [reply]
Hey @razvanilin I believe I'm using the latest version. I pulled from dockerhub (unless I need to build from source instead?)

```yaml
...
  chartbrewdb:
    image: mysql:5.7
    restart: always
    env_file:
      - chartbrew.env
    volumes:
      - ./chartbrew-db:/var/lib/mysql
  chartbrew:
    image: razvanilin/chartbrew
    restart: always
    env_file:
      - chartbrew.env
    ports:
      - 4019:4019
      - 4018:4018
      - 3000:3000
    depends_on:
      - chartbrewdb
...
```
