### DISCUSSION TITLE
Deploying Chartbrew by using Traefik

### DISCUSSION THREAD

**Discussion by lcfd** [chartbrew/chartbrew#134] [Q&A]
Hi!

I'm trying to deploy Chartbrew by using Traefik in docker-compose but without much fortune.
I was successful in serving the front end but without a working backend.

Are there examples of doing it? Or by any chance, someone tried to do it?

Thank you!

**Comment by razvanilin** [comment]
Hey @lcfd I'm not familiar with Traefik. Can you post here something you've tried (e.g. your docker-compose)? I can try and give it a go to see how it goes :)

**Reply by lcfd** [reply]
Hello, thank you for your attention. 

Here is the chartbrew configuration that I have in my docker-compose file.

```
chartbrew:
  image: "razvanilin/chartbrew:latest"
  container_name: chartbrew
  restart: unless-stopped
  env_file:
    - "<path to my env file>"
  depends_on:
    traefik:
      condition: service\_started
    db:
      condition: service\_started
  labels:
    - "traefik.enable=true"
    - "traefik.http.routers.chartbrew.rule=Host(`mydomain.com`)"
    - "traefik.http.routers.chartbrew.entrypoints=https"
    - "traefik.http.routers.chartbrew.tls=true"
    - "traefik.http.services.chartbrew.loadbalancer.server.port=3000"
```

In the `.env` file I have:

```
CB_DB_NAME=chartbrew
CB_DB_USERNAME=<username>
CB_DB_PASSWORD=<password>
CB_DB_HOST=db
CB_DB_PORT=5432
CB_DB_DIALECT=postgres

CB_API_HOST=mydomain.com
CB_API_PORT=4019
REACT_APP_CLIENT_HOST=https://mydomain.com
REACT_APP_API_HOST=https://mydomain.com:4019
```

The port management is a bit confusing.
