### DISCUSSION TITLE
Traefik 2 setup with CORS

### DISCUSSION THREAD

**Discussion by filcuk** [chartbrew/chartbrew#248] [Q&A]
Would anyone using Traefik have a working compose to share?
I've not been able to get this going.
All setups I've done up until now had the API running in a standalone container, or communicating internally in a single container.

Here's the current setup:
```
    environment:
      ...
      CB_API_HOST: 0.0.0.0
      CB_API_PORT: 4019
      VITE_APP_CLIENT_HOST: https://chartbrew.${DOMAINNAME2}:4018
      VITE_APP_CLIENT_PORT: 4018
      VITE_APP_API_HOST: https://chartbrew.${DOMAINNAME2}:4019
      ...
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chartbrew-rtr.entrypoints=https"
      - "traefik.http.routers.chartbrew-rtr.rule=Host(`chartbrew.${DOMAINNAME2}`)"
      - "traefik.http.routers.chartbrew-rtr.middlewares=chartbrew-cors@docker,chain-no-auth@file"
      - "traefik.http.routers.chartbrew-rtr.service=chartbrew-svc"
      - "traefik.http.services.chartbrew-svc.loadbalancer.server.port=4018"
      - "traefik.http.middlewares.chartbrew-cors.headers.customResponseHeaders.accessControlAllowOriginList=https://chartbrew.${DOMAINNAME2}"
      - "traefik.http.middlewares.chartbrew-cors.headers.customResponseHeaders.accessControlAllowMethods=GET,POST,OPTIONS"
```

![image](https://github.com/user-attachments/assets/a14de3a9-f87b-4271-ba6c-e2331bf40ca2)
