### ISSUE TITLE
Help with nginx configuration

### ISSUE THREAD

**Issue by edleeman17** [chartbrew/chartbrew#131]
Hey!

I was wondering whether you could help me?

I'm struggling to get Chartbrew working with my nginx configuration.

I have Chartbrew running in Docker + Docker Compose. I have cloned Chartbrew from the Github Repo

docker-compose.yml
```yaml
version: '3.8'
services:
  nginx:
    build: ./nginx
    ports:
      - 8080:80
    depends_on:
      - storefront
      - storefront-functions
      - strapi
    restart: unless-stopped
  chartbrewdb:
    image: mysql:5.7
    restart: always
    env_file:
      - chartbrew.env
    volumes:
      - ./chartbrew-db:/var/lib/mysql
  chartbrew:
    build: ./chartbrew
    restart: always
    env_file:
      - chartbrew.env
    depends_on:
      - chartbrewdb
```

nginx.conf
```
server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    location /chart-api {
        proxy_pass http://chartbrew:4019;
        rewrite ^/chart-api/?(.*)$ /$1 break;
    }

    location /charts {
        rewrite ^/charts/?(.*)$ /$1 break;
        proxy_set_header HOST $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        
        proxy_pass http://chartbrew:3000;
    }
}
```

environment variables
```
MYSQL_DATABASE: chartbrew
MYSQL_USER: chartbrew
MYSQL_PASSWORD: secret_password
MYSQL_ALLOW_EMPTY_PASSWORD: 1

CB_SECRET=enter_a_secure_string
CB_API_HOST=
CB_API_PORT=4019
CB_DB_HOST=chartbrewdb
CB_DB_NAME=chartbrew
CB_DB_USERNAME=chartbrew
CB_DB_PASSWORD=secret_password
REACT_APP_CLIENT_HOST=http://localhost:8080/chart-api
REACT_APP_API_HOST=http://localhost:8080/charts
```

I run `docker-compose build && docker-compose up`

Builds fine and spins up. However...

![image](https://user-images.githubusercontent.com/61695425/182187907-20bbfe6e-87f2-4db2-b447-4e7afa40daca.png)

The static files are not using my `/charts` route correctly.

Any assistance would be amazing, thank you!
