### ISSUE TITLE
I'm getting segmentation fault when trying to deploy the container

### ISSUE THREAD

**Issue by panosru** [chartbrew/chartbrew#205]
I think that I followed the guides properly but I might've missed something... 

Here is the output I get when I run `BASE_URL=http://localhost docker compose up chartbrew`

```
BASE_URL=http://localhost docker compose up chartbrew
[+] Running 7/7
 ✔ Network strapi_default      Created                                                                                                                                                        0.0s
 ✔ Volume "strapi_chartbrew"   Created                                                                                                                                                        0.0s
 ✔ Volume "strapi_pgdata"      Created                                                                                                                                                        0.0s
 ✔ Container strapi-db         Created                                                                                                                                                        0.4s
 ✔ Container strapi-chartbrew  Created                                                                                                                                                        1.0s
Attaching to strapi-chartbrew
strapi-chartbrew  | The UI is rebuilding. Please wait...
strapi-chartbrew  |
strapi-chartbrew  | > client-new@v3.1.1 preview
strapi-chartbrew  | > vite preview
strapi-chartbrew  |
strapi-chartbrew  |
strapi-chartbrew  | > client-new@v3.1.1 build
strapi-chartbrew  | > npm run prepareSettings && vite build
strapi-chartbrew  |
strapi-chartbrew  |
strapi-chartbrew  | > client-new@v3.1.1 prepareSettings
strapi-chartbrew  | > echo n | cp -vipr src/config/settings.template.js src/config/settings.js | true
strapi-chartbrew  |
strapi-chartbrew  | cp: overwrite 'src/config/settings.js'? Segmentation fault
strapi-chartbrew  | Segmentation fault
strapi-chartbrew exited with code 139
```

And this is my docker compose YAML file:

```yaml
version: '3.9'

services:

  chartbrew:
    image: razvanilin/chartbrew
    container_name: 'strapi-chartbrew'
    logging:
      driver: "json-file"
      options:
        max-size: '1m'
        max-file: '1'
    #restart: always
    ports:
      - "4018:4018"
      - "4019:4019"
    expose:
      - 4018
      - 4019
    environment:
      CB_SECRET: ${ADMIN_PASSWORD:-chartbrew}
      CB_API_HOST: 0.0.0.0
      CB_API_PORT: 4019
      CB_DB_DIALECT: postgres
      CB_DB_HOST: db
      CB_DB_PORT: 5432
      CB_DB_NAME: chartbrew
      CB_DB_USERNAME: strapi
      CB_DB_PASSWORD: strapi
      VITE_APP_CLIENT_HOST: "${BASE_URL}:4018"
      VITE_APP_CLIENT_PORT: 4018
      VITE_APP_API_HOST: "${BASE_URL}:4019"
    volumes:
      - chartbrew:/code/client/dist
    depends_on:
      - db
  
  db:
    image: postgres:16.2-alpine
    container_name: 'strapi-db'
    healthcheck:
      test: [ "CMD", "pg_isready", "-h", "localhost",
          "-p", "5432", "-U", "${POSTGRES_USER:-strapi}"]
      interval: 10s
      timeout:  5s
      retries:  3
    logging:
      driver: "json-file"
      options:
        max-size: '1m'
        max-file: '1'
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:-strapi}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-strapi}
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
      LANG: en_US.utf8
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres.init.sql:/docker-entrypoint-initdb.d/postgres.init.sql

volumes:
  chartbrew: {}
  pgdata: {}
```

The content of `postgres.init.sql` is this:
```sql
CREATE DATABASE "chartbrew"
    WITH
    OWNER = strapi
    ENCODING = 'UTF8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;
    
CREATE DATABASE "strapi"
    WITH
    OWNER = strapi
    ENCODING = 'UTF8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;
```

I have also tried with MySQL and I was getting the same result.

Thanks!
