### ISSUE TITLE
Running the application with Docker CORS error

### ISSUE THREAD

**Issue by ketlinapuci** [chartbrew/chartbrew#260]
Hi, I am trying to install the app using docker in one of my vps 
This is docker-compose.yml file content
version: '3.7'

```
services:
  chartbrew:
    image: razvanilin/chartbrew
    ports:
      - "4018:4018"
      - "4019:4019"
    environment:
      CB_API_HOST: 0.0.0.0
      CB_API_PORT: 4019
      CB_DB_HOST: 149.0.0.0 (Ip is for demontstration purpose)
      CB_DB_PORT: 3306
      CB_DB_NAME: chartbrew_db
      CB_DB_USERNAME: root
      CB_DB_PASSWORD: ""
      CB_REDIS_HOST: redis
      CB_REDIS_PORT: 6379
      CB_REDIS_PASSWORD: password
      VITE_APP_CLIENT_HOST: http://149.0.0.0:4018 (Ip is for demontstration purpose)
      VITE_APP_CLIENT_PORT: 4018
      VITE_APP_API_HOST: http://149.0.0.0:4019

  redis:
    image: redis
    environment:
      REDIS_PASSWORD: password
    ports:
      - "6380:6379"
  ```
  
  When I start the app, I get access to the UI If I got to server Ip and port 4018, 
  
![image](https://github.com/user-attachments/assets/7cef81cb-8c3d-49f1-9c6f-4b6edba46580)
But I  can't register and login and get a CORS error in console like:
 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://149.102.141.128:4019/user/relog. (Reason: CORS request did not succeed). Status code: (null).
 Could you help me to review is something is wrong in configurations that is causing this ?
