### ISSUE TITLE
Dashboard report throws `R.entries().forEach is not a function`

### ISSUE THREAD

**Issue by michalpulpan** [chartbrew/chartbrew#270]
Hi, 

first of all, thank you for an amazing product. We found out about Chartbrew and immediately spun up our instance. However, when trying to ten reports, we see following:

**Describe the bug**
When opening "Dashboard reports" for dashboard with > 1 widget we get following error in the browser viewport:
```
Unexpected Application Error!
R.entries().forEach is not a function. (In 'R.entries().forEach(k=>{const[C,L]=k;if(C.startsWith("fields[")){let z=C.replace("fields[","");z=z.substring(0,z.length-1),z.includes("root[].")||(z=`root[].${z}`),o.push({field:z,value:L,operator:"is",project_id:t.id})}})', 'R.entries().forEach' is undefined)
Se@https://chartbrew.ourdomain.com/assets/PublicDashboard-YSslrbPG.js:1:24317
@https://chartbrew.ourdomain.com/assets/PublicDashboard-YSslrbPG.js:1:23204
i6@https://chartbrew.ourdomain.com/assets/index-Cauyk0m2.js:41:24359
eT@https://chartbrew.ourdomain.com/assets/index-Cauyk0m2.js:41:42602
Vee@https://chartbrew.ourdomain.com/assets/index-Cauyk0m2.js:41:36766
MS@https://chartbrew.ourdomain.com/assets/index-Cauyk0m2.js:39:3303
jMe@https://chartbrew.ourdomain.com/assets/index-Cauyk0m2.js:41:41473
g_@https://chartbrew.ourdomain.com/assets/index-Cauyk0m2.js:41:40456
xge@https://chartbrew.ourdomain.com/assets/index-Cauyk0m2.js:41:35871
be@https://chartbrew.ourdomain.com/assets/index-Cauyk0m2.js:26:1670
xe@https://chartbrew.ourdomain.com/assets/index-Cauyk0m2.js:26:2061
```

However, when the dashboard has zero widgets, the error does not occur.

**To Reproduce**
1. Create new dashboard
2. Add widget from some dataset
3. Open Dashboard reports
4. You get error in the window

https://github.com/user-attachments/assets/2ee48d0a-cbcc-4605-8356-a34ca8d78624

**Expected behavior**
Allow users to generate the report.

**Screenshots**

**Desktop (please complete the following information):**
- Docker compose:
```yaml
services:
  db:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      # These values are taken from the .env file
      MYSQL_DATABASE: ${CB_DB_NAME}
      MYSQL_USER: ${CB_DB_USERNAME}
      MYSQL_PASSWORD: ${CB_DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: true
      MYSQL_DEFAULT_AUTH: caching_sha2_password
    ports:
      - 3307:3306
    volumes:
      - ./chartbrew-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    mem_limit: 1500m        # ~1.5GB
    memswap_limit: 1500m    # Ensures it won't use more swap
    cpus: "0.5"

  redis:
    image: redis:alpine
    restart: unless-stopped
    environment:
      CB_REDIS_HOST: redis
      REDIS_PASSWORD: ${CB_REDIS_PASSWORD}
    ports:
      - 6377:6379
    mem_limit: 256m
    memswap_limit: 256m
    cpus: "0.25"

  chartbrew:
    image: razvanilin/chartbrew
    restart: unless-stopped
    env_file: .env
    ports:
      - 4018:4018 # Frontend
      - 4019:4019 # API
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    links:
      - db
      - redis
    mem_limit: 3500m
    memswap_limit: 3500m

    cpus: "1.0"

volumes:
  chartbrew-db:
```

with following `.env`:

```env
#### PRODUCTION VARS ####

### Database connection parameters
CB_DB_NAME=chartbrew
CB_DB_USERNAME=chartbrew
CB_DB_PASSWORD=<>
CB_DB_HOST=db
CB_DB_PORT=3306
CB_DB_CERT=
CB_DB_SSL=
CB_DB_SSL_KEY=
CB_DB_SSL_CERT=

# set to 'mysql' or 'postgres'
CB_DB_DIALECT=mysql

# Redis connection parameters
CB_REDIS_HOST=redis
CB_REDIS_PORT=6379
CB_REDIS_PASSWORD=

### A secret string which will be used to encrypt your data
CB_ENCRYPTION_KEY=<>

### The API host string used on the server app
# Set this to 0.0.0.0 when using docker AND proxying it through apache or nginx
CB_API_HOST=0.0.0.0
CB_API_PORT=4019

### Used in the client app

# The address where the front-end app sits and port
VITE_APP_CLIENT_HOST=https://chartbrew.ourdomain.com
VITE_APP_CLIENT_PORT=4018

# The address where the backend API sits
VITE_APP_API_HOST=https://api.chartbrew.ourdomain.com

# Email connection parameters for sending team signup invites and forgot password emails
CB_MAIL_HOST=<>
CB_MAIL_USER=<>
CB_MAIL_PASS=<>
CB_MAIL_PORT=465
CB_MAIL_SECURE=true
# The admin email from which all the emails are delivered
CB_ADMIN_MAIL=<>

# Restrict users from having their own team
# 0 - users will have their own team
# 1 - users can only be part of teams they are invited to
CB_RESTRICT_TEAMS=0

# Restrict users from creating their own accounts unless invited
# 0 - users can create their own accounts
# 1 - users can only create accounts with invite links
CB_RESTRICT_SIGNUP=0

# Google cloud client ID information (To enable Google integrations)
CB_GOOGLE_CLIENT_ID=
CB_GOOGLE_CLIENT_SECRET=

# OpenAI API key
CB_OPENAI_API_KEY=<>
CB_OPENAI_MODEL=gpt-4o-mini

```

Thank you in advance!
